config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      :registrations  => 'users/registrations',
      :sessions       => 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "sign_in",    to: "users/sessions#new"
    get "sign_out",   to: "users/sessions#destroy"
    get "users/:id",  to: "users/registrations#show"
    get "users",      to: "users/registrations#index"
  end

  get 'posts/search', to: 'posts#search'
  get '/home',        to: 'static_pages#home'
  get '/agreement',   to: 'static_pages#agreement'
  root "posts#index"

  resources :favorites,     only: [:create, :destroy]
  resources :posts
  resources :comments,      only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index]
  resources :users do
    member do
      get :following, :followers
      # GET /users/1/following
      # GET /users/1/followers
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments,       dependent: :destroy
  has_many :favorites,      dependent: :destroy
  has_many :notifications,  dependent: :destroy

  default_scope -> { self.order(created_at: :desc) }

  validates :user_id,
    presence: true
  validates :title,
    presence: true,
    length: { maximum: 20 }
  validates :description,
    length: { maximum: 140 }

  def self.search(keyword)
    return Post.all unless keyword
    # titleカラム,descriptionカラムにkeywordが含まれているものを取得
    Post.where("title LIKE ? OR description LIKE ?", "%#{keyword}%", "%#{keyword}%")
  end

  def self.latest(current_user_following)
    latest_posts = []
    Post.all.each do |post|
      if current_user_following.include?(post.user)
        latest_posts << post
      end
    end
    latest_posts
  end

  # 通知機能の実装
  def create_notification_like(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: user_id,
        post_id: id,
        action: 'favorite'
      )
      notification.save if notification.valid?
    end
  end

  def create_notification_comment(current_user)
    # すでに「コメント」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'comment'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: user_id,
        post_id: id,
        action: 'comment'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  after_action :invoke_html_or_javascript, only: [:show]

  def index
    # 全ての投稿写真の中から、フォローしているユーザーの投稿写真を取り出す
    @latest_posts = Post.latest(current_user.following)
    # ページネーション
    # 通常pageメソッドはActive Recordのオブジェクトにしか適用されないので次の書き方はエラー
    # @latest_posts = Post.latest(current_user.following).paginate(page: params[:page], per_page: 9)
    @latest_posts = Kaminari.paginate_array(@latest_posts).page(params[:page]).per(9)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    # @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "投稿しました"
      # リダイレクト先で自動でモーダル表示できるように、クエリパラメータに投稿写真のidを含める、
      redirect_to "/users/#{current_user.id}/?post_with_quick_modal=#{@post.id}"
    else
      flash[:danger] = "投稿できませんでした"
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      @post.attributes = post_params # 特定のカラムのみ代入し、DBには保存しない
      # @post.image.attach(params[:post][:image])
      if @post.save
        flash[:success] = "編集しました"
        # リダイレクト先で自動でモーダル表示できるように、クエリパラメータに投稿写真のidを含める、
        redirect_to "/users/#{current_user.id}/?post_with_quick_modal=#{@post.id}"
      else
        flash[:danger] = "編集できませんでした"
        render "edit"
      end
    else
      flash[:danger] = "他のユーザーの投稿は編集できません"
      redirect_to "/users/#{current_user.id}"
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      @post.destroy
      flash[:success] = "投稿を削除しました"
    else
      flash[:danger] = "他のユーザーの投稿は削除できません"
    end
    redirect_to "/users/#{current_user.id}"
  end

  def search
    @posts = Post.search(params[:keyword]).page(params[:page]).per(9)
    @keyword = params[:keyword]
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image, :image_cache)
  end
end

app/views/posts/_form.html.erb
<div class="container post_form-section">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2 class="post_form-section__page-title"><%= headline %></h2>

      <%= form_for(post) do |f| %>
        <%= render 'layouts/error_messages', model: post %>

        <div class="form-group post_form-section__form-group">
          <%= f.label :title, "タイトル" %>
          <%= f.text_field :title, class: "form-control input-lg" %>
        </div>

        <div class="image">
          <%= f.label :image, "ファイル選択", class: "file-field-label" %>
          <%= f.file_field :image %>
          <!--画像をキャッシュする。
          カラム名_cacheとする。
          Strong Parametersの方にも追加。
          これがない場合は、バリデーションエラーでフォーム再表示したときに、
          画像を再び選択しないとデータベースに更新されない-->
          <%= f.hidden_field :image_cache %>
          <% if post.image? %>
            <%= image_tag post.image.url, id: 'img1', class: "post_form-section__image" %>
          <% else %>
            <%= image_tag "default_post.png", id: 'img1', class: "post_form-section__image" %>
          <% end %>
        </div>

        <div class="form-group post_form-section__form-group">
          <%= f.label :description, "ひとこと" %>
          <%= f.text_area :description, class: "form-control input-lg" %>
        </div>

        <div class="post_form-section__btn-area">
          <%= f.submit "アップロード", class: "btn post_form-section__btn-custom" %>
        </div>

      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>

</div>


<!-----------------------------選択した画像をプレビュー----------------------------->
<%= javascript_pack_tag 'preview_post' %>

app/views/posts/_modal_trial.html.erb
<div class="photomodal" >
  <%= image_tag(@post.image.url, class: "photomodal__image")  %>
  <div class="photomodal__host">
    <div class="row user-small-thumbnail">
      <div class="col-md-4">
        <!-- アバター画像がある場合のみ表示 -->
        <% if @post.user.avatar? %>
          <%= link_to image_tag(@post.user.avatar.url, class: "user-small-thumbnail__image"), "#{root_url(only_path: false)}users/#{current_user.id}" %>
        <% end %>

        <p class="user-name user-small-thumbnail__name"><%= @post.user.name %></p>
        <div id="comments-count">
          <p><%= @post.comments.count %>コメント</p>
        </div>

        <!-- カレントユーザーと投稿主が異なるならお気に入りに登録できる -->
        <% unless current_user == @post.user %>
          <div id="favorite-form">
            <% if current_user.adding?(@post) %>
              <%= render 'favorites/remove', post: @post %>
            <% else %>
              <%= render 'favorites/add', post: @post %>
            <% end %>
          </div>
        <% end %>

        <div id="favorites-count">
          <p><%= @post.favorites.count %>いいね</p>
        </div>
      </div>

      <div class="col-md-8">
        <h3 class="photomodal__title"><%= @post.title %></h3>
        <p class="photomodal__description"><%= @post.description %></p>
        <div class="photomodal__detail row">

          <!-- 写真投稿主とカレントユーザーが同じなら編集、削除できる -->
          <% if @post.user == current_user %>
            <div class="col-md-8">
              <p class="photomodal__time"><%= time_ago_in_words(@post.created_at) %>前に投稿</p>
              <!-- 編集された場合のみ編集時刻を表示させる -->
              <% unless @post.created_at == @post.updated_at %>
                <p class="photomodal__time"><%= time_ago_in_words(@post.updated_at) %>前に編集</p>
              <% end %>
            </div>
            <div class="col-md-2 current-user-link--post-edit" id="post-edit"><%= link_to "編集", edit_post_path %></div>
            <div class="col-md-2 current-user-link--post-delete" id="post-delete"><%= link_to "削除", post_path(@post.id), method: :delete %></div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div class="photomodal__comments">

    <!-- カレントユーザーのコメント -->
    <div id="current-user-comment" class="row user-tiny-thumbnail">
      <!--TODO Ajaxリクエストを送る前後で, html構造がややこしく変化している。改善が必要。-->
      <div id="hidden-for-ajax">
        <div>
          <% comment = @post.comments.find_by(user_id: current_user.id) %>
        </div>
      </div>


      <div id="comment-not-yet">
        <div>
          <!-- 投稿写真が他ユーザーのものである、かつ、コメントしていないとき -->
          <% if current_user != @post.user && comment == nil %>
            <%= render partial: 'comments/new_comment.html.erb', locals:  {post: @post, comment: nil} %>
          <% end %>
        </div>
      </div>


      <div id="comment-done">
        <div>
          <!-- 投稿写真が他ユーザーのものである、かつ、コメント済みのとき -->
          <% if current_user != @post.user && comment != nil %>
            <%= render 'comments/output_comments', {post: @post, comment: comment} %>
          <% end %>
        </div>
      </div>
    </div>

    <!--他ユーザーのコメント-->
    <div class="others-comments">
      <% if @post.comments.any? %>
        <li class="others-comments__list"><%= render partial: 'comments/comment', collection: @post.comments %></li>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/_post.html.erb
<div class="postcard" id="post-<%= post.id %>">
  <!-- 投稿写真を表示 -->
  <% unless post.image.nil? %>
    <%= link_to image_tag(post.image.url, class: "posted-content__image", alt: "post-#{post.id}"), "/posts/#{post.id}", remote: true %>
  <% end %>


  <!-- お気に入りの投稿、または、最新の投稿を表示するときは複数の写真投稿主が混在するため、わかるように投稿主のサムネイルを小さく載せる -->
  <% unless favorite_or_latest_posts.nil? %>
    <div class="posted-user-tiny-thumbnail">
      <!-- アバター画像があれば表示する -->
      <% if post.user.avatar? %>
        <%= link_to image_tag(post.user.avatar.url, class: "posted-user-tiny-thumbnail__image"), "/users/#{post.user.id}"  %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
      <% end %>
      <p class="posted-user-tiny-thumbnail__name"><%= post.user.name %></p>
    </div>
    <!-- 投稿写真左上にサムネイル表示スペースをつくる -->
    <div class="triangle"></div>
  <% end %>

</div>

app/views/posts/edit.html.erb
<% provide(:title, "投稿編集") %>
<%= render "posts/form", headline: "投稿を編集", post: @post %>

app/views/posts/index.html.erb
<% provide(:title, "最新の投稿") %>
<div id="modal-container" class="new-post-modal">
  <div class="photomodal -hidden">
  </div>
</div>
<div class="container user-section">
  <h2 class="user-section__page-title">最新の投稿</h2>
  <!-----------------------------最新の投稿----------------------------->
  <div class="posts">
    <% if @latest_posts.any? %>
      <li class="posts__list"><%= render partial: 'posts/post', locals:  {favorite_or_latest_posts: @latest_posts}, collection: @latest_posts %></li>
    <% end %>
  </div>
  <%= paginate @latest_posts %>
</div>

<!-----------------------------モーダルをスイッチ----------------------------->
<%= javascript_pack_tag 'switch_modal' %>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>
<%= render "posts/form", headline: "新規投稿", post: @post %>

app/views/posts/search.html.erb
<% provide(:title, "検索結果") %>

<div id="modal-container" class="searched-post-modal">
  <div class="photomodal -hidden">
  </div>
</div>

<div class="container user-section">
  <h2 class="sign-up-section__page-title">[<%= @keyword %>]の検索結果</h2>
  <div class="" id="search-posts-content">
    <div class="posts">
      <% if @posts.any? %>
        <li class="posts__list"><%= render partial: 'posts/post', locals:  {favorite_or_latest_posts: @posts}, collection: @posts %></li>
      <% end %>
    </div>
  </div>
  <%= paginate @posts %>
</div>

<!-----------------------------モーダルをスイッチ----------------------------->
<%= javascript_pack_tag 'switch_modal' %>

app/views/posts/show.js.erb
$('#modal-container').html("<%= j (render 'posts/modal_trial') %>");