config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      :registrations  => 'users/registrations',
      :sessions       => 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "sign_in",    to: "users/sessions#new"
    get "sign_out",   to: "users/sessions#destroy"
    get "users/:id",  to: "users/registrations#show"
    get "users",      to: "users/registrations#index"
  end

  get 'posts/search', to: 'posts#search'
  get '/home',        to: 'static_pages#home'
  get '/agreement',   to: 'static_pages#agreement'
  root "posts#index"

  resources :favorites,     only: [:create, :destroy]
  resources :posts
  resources :comments,      only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index]
  resources :users do
    member do
      get :following, :followers
      # GET /users/1/following
      # GET /users/1/followers
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="container header">
    <div class="row">

      <div class="col-md-4">
        <% if current_user.nil?%>
          <a href="/home" class="navbar-brand header__logo">Instaclone</a>
        <% else %>
          <a href="/" class="navbar-brand header__logo">Instaclone</a>
        <% end %>
      </div>

      <div class="col-md-3"></div>

      <div class="col-md-5 header__links">

        <%= link_to image_tag("camera.png" , class: "header__image"), new_post_path %>

        <% if user_signed_in? %>
          <!--例えばposts/newのページからリンクを押すとposts/users/1のようにpostsの後にusersがきてしまうので使わない-->
          <%#= link_to image_tag("person.png", class: "header__image"), "users/#{current_user.id}" %>
          <!--絶対パスで指定する-->
          <%= link_to image_tag("person.png", class: "header__image"), "#{root_url(only_path: false)}users/#{current_user.id}" %>
        <% else %>
          <%= link_to image_tag("person.png", class: "header__image"), sign_in_path %>
        <% end %>

        <%= link_to image_tag("bell.png", class: "header__image"), notifications_path %>
        <% if unchecked_notifications_any? %>
          <div class="notification__circle"></div>
        <% end %>

        <div>
          <%= form_tag("/posts/search", method: "get", class: "search") do %>
            <%= label_tag(:keyword, "Search for:", class: "search__label") %>
            <%= text_field_tag :keyword, '', class: 'search__input' %>
            <%= image_submit_tag "search.png", class: "search__btn" %>
          <% end %>
        </div>

      </div>

    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177848854-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-177848854-1');
    </script>

    <title><%= yield(:title) %> | Instaclone</title>
    <meta name="description" content="アルバムをシェア！いいねやコメントをもらおう。何気ない日常が繋がりをつくる。">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container flash-bar">
      <% flash.each do |message_type, message| %><!--message_typeはflashのkey,messageはflashのvalue-->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>

    <% if Rails.env.development? %>
      <br>
      <%= "@user.name :  #{@user.name}" unless @user == nil  %>
      <br>
      <%= "@user.id :  #{@user.id}" unless @user == nil  %>
      <br>
      <br>
      <div class="testertag">
        <%= "current_user.name :  #{current_user.name}" unless current_user.nil?  %>
        <br>
        <%= "current_user.id :  #{current_user.id}" unless current_user.nil?  %>
        <%= debug(params) %>
      </div>
    <% end %>

  </body>
</html>